import types

from _typeshed import Incomplete
from statsd.client.base import StatsClientBase

def safe_wraps(wrapper, *args, **kwargs): ...

class Timer:
    client: Incomplete
    stat: Incomplete
    rate: Incomplete
    ms: Incomplete
    def __init__(self, client: StatsClientBase, stat: str, rate: int = 1) -> None: ...
    def __call__(self, f): ...
    def __enter__(self): ...
    def __exit__(self, typ: type[BaseException] | None, value: BaseException | None, tb: types.TracebackType | None) -> None: ...
    def start(self): ...
    def stop(self, send: bool = True): ...
    def send(self) -> None: ...
